//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Blogs.Entity
{
    public partial class blog_tb_article : FYJ.Entity.EntityBase
    {
        public int articleID { get; set; }
        public int blogID { get; set; }
        public int siteCategoryID { get; set; }
        public int categoryID { get; set; }
        public int topicID { get; set; }
        public string articleTitle { get; set; }
        public string articleTitleColor { get; set; }
        public string articleKeywords { get; set; }
        public string articleDescription { get; set; }
        public string articleSource { get; set; }
        public string articleAuthor { get; set; }
        public string articleSourceUrl { get; set; }
        public string articlePic { get; set; }
        public string articleThumbPic { get; set; }
        public System.DateTime articleDatetime { get; set; }
        public string articleRedirectUrl { get; set; }
        public string articleAddUserID { get; set; }
        public string articleModifyUserID { get; set; }
        public int articleOrder { get; set; }
        public int articleReplyCount { get; set; }
        public bool articleIsTop { get; set; }
        public bool articleIsDisabled { get; set; }
        public int articleCommentLimit { get; set; }
        public bool articleIsIndex { get; set; }
        public bool articleIsOriginal { get; set; }
        public bool articleIsSystem { get; set; }
        public bool articleIsPic { get; set; }

        public bool articleIsHidden { get; set; }

        public bool articleIsDelete { get; set; }
        public int articleAttachmentLimit { get; set; }
        public string articlePassword { get; set; }
        public string articlePostBy { get; set; }
        public string themeID { get; set; }

        public bool IsShowSource { get; set; }

        public System.DateTime ADD_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }

    }
}
