//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogs.Entity
{
    using FYJ;
    using System;
    using System.Collections.Generic;

    public partial class blog_tb_menu : FYJ.Entity.EntityBase
    {
        public string menuID { get; set; }
        public int blogID { get; set; }
        public string parentID { get; set; }
        public string menuClass { get; set; }
        public string menuName { get; set; }
        public string menuDisplay { get; set; }
        public string menuUrl { get; set; }
        public string menuPic { get; set; }
        public int menuOrder { get; set; }
        public bool menuIsDisabled { get; set; }
        public string menuTarget { get; set; }
        public System.DateTime ADD_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }

        [Ignore]
        public int rowcount { get; set; }

        [Ignore]
        public blog_tb_menu[] children
        {
            get;
            set;
        }


        [Ignore]
        public string TextWithTreeSpace { get; set; }

        /// <summary>
        /// 层次深度  0开始
        /// </summary>
        [Ignore]
        public int treeDeep { get; set; }

        [Ignore]
        public string id { get { return menuID; } }

    }
}
