//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogs.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class blog_tb_comment : FYJ.Entity.EntityBase
    {
        public string commentID { get; set; }
        public string parentID { get; set; }
        public int articleID { get; set; }
        public string userID { get; set; }
        public string userName { get; set; }
        public string commentIP { get; set; }
        public string commentCountry { get; set; }
        public string commentCity { get; set; }
        public string commentContent { get; set; }
        public string commentText { get; set; }
        public int commentState { get; set; }
        public Nullable<int> floor { get; set; }
        public int supportCount { get; set; }
        public int againstCount { get; set; }
        public System.DateTime ADD_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
